# Generated by Django 2.0.7 on 2019-02-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0002_auto_20190208_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lsd',
            name='a1',
        ),
        migrations.RemoveField(
            model_name='lsd',
            name='a2',
        ),
        migrations.RemoveField(
            model_name='lsd',
            name='a3',
        ),
        migrations.AddField(
            model_name='lsd',
            name='name',
            field=models.CharField(default='regular', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lsd',
            name='nos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lsd',
            name='summary',
            field=models.TextField(default='its dope..'),
        ),
    ]
