# Generated by Django 2.0.7 on 2019-03-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user1',
        ),
        migrations.AddField(
            model_name='cart',
            name='prod',
            field=models.ManyToManyField(blank=True, to='appx.lsd'),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
