# Generated by Django 2.0.7 on 2019-03-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cate', models.CharField(max_length=25)),
                ('nos', models.IntegerField(blank=True, default=0)),
                ('featu', models.CharField(default='none', max_length=55)),
            ],
        ),
    ]
